baseURL = "https://farsalinos.github.io/"
locale = "en"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true
buildDrafts = false
enableEmoji = true
pagination.pagerSize = 10

[outputs]
  home = ["html", "json"]
  section = ["html", "json"]
  taxonomy = ["html", "json"]
  term = ["html", "json"]

[module]
  [[module.imports]]
    path = "github.com/nunocoracao/blowfish/v3"