baseURL = "https://farsalinos.github.io/"
locale = "en"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true
theme = "blowfish"
buildDrafts = false
enableEmoji = true
pagination.pagerSize = 10